name: CMake on a single platform

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir sup_part
        git submodule add https://github.com/google/googletest sup_part/gtest
        cd sup_part/gtest && git checkout release-1.11.0 && cd ../..
        cmake -H. -B build
        cmake --build build
        
    - name: Tests
      run: |
        build/check
